name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer kivy[base] kivymd cython
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        
    - name: Setup Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Try multiple download methods with retries
        for i in {1..3}; do
          if wget --timeout=30 --tries=3 -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip; then
            break
          elif curl -L --connect-timeout 30 --max-time 300 -o commandlinetools-linux-8512546_latest.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip; then
            break
          else
            echo "Download attempt $i failed, retrying..."
            sleep 10
          fi
        done
        
        if [ ! -f commandlinetools-linux-8512546_latest.zip ]; then
          echo "Failed to download Android SDK tools after 3 attempts"
          exit 1
        fi
        
        unzip -q commandlinetools-linux-8512546_latest.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mkdir -p android-sdk/tools/bin
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        # Create symlinks for buildozer compatibility
        ln -s ../cmdline-tools/latest/bin/sdkmanager android-sdk/tools/bin/sdkmanager
        ln -s ../cmdline-tools/latest/bin/avdmanager android-sdk/tools/bin/avdmanager
        
        export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/tools/bin
        yes | sdkmanager --licenses
        sdkmanager "build-tools;30.0.3" "platforms;android-30" "platform-tools"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/30.0.3" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/tools/bin" >> $GITHUB_PATH
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
